# translation missing: fr-FR, rights, __admin__
__admin__:
  actions:
  - articles::activate
  - articles::articles_dyta
  - articles::authors_dyli
  - articles::create
  - articles::deactivate
  - articles::destroy
  - articles::edit
  - articles::help
  - articles::index
  - articles::new
  - articles::preview
  - articles::publish
  - articles::show
  - articles::update
  - configurations::edit
  - configurations::update
  - countries::create
  - countries::destroy
  - countries::edit
  - countries::index
  - countries::new
  - countries::update
  - images::create
  - images::destroy
  - images::edit
  - images::index
  - images::new
  - images::show
  - images::update
  - languages::create
  - languages::destroy
  - languages::edit
  - languages::index
  - languages::new
  - languages::update
  - mandate_natures::create
  - mandate_natures::destroy
  - mandate_natures::edit
  - mandate_natures::index
  - mandate_natures::new
  - mandate_natures::update
  - mandates::create
  - mandates::destroy
  - mandates::edit
  - mandates::index
  - mandates::mandates_dyta
  - mandates::new
  - mandates::people_dyli
  - mandates::update
  - people::activate
  - people::approve
  - people::create
  - people::destroy
  - people::disapprove
  - people::edit
  - people::index
  - people::lock
  - people::new
  - people::people_dyta
  - people::person_articles_dyta
  - people::person_mandates_dyta
  - people::person_subscriptions_dyta
  - people::show
  - people::story
  - people::subscribe
  - people::unlock
  - people::update
  - rubrics::create
  - rubrics::destroy
  - rubrics::edit
  - rubrics::index
  - rubrics::new
  - rubrics::rubric_articles_dyta
  - rubrics::rubrics_dyta
  - rubrics::show
  - rubrics::update
  - zone_natures::create
  - zone_natures::destroy
  - zone_natures::edit
  - zone_natures::index
  - zone_natures::new
  - zone_natures::update
  - zones::create
  - zones::destroy
  - zones::edit
  - zones::index
  - zones::new
  - zones::refresh
  - zones::show
  - zones::update
# translation missing: fr-FR, rights, __private__
__private__:
  actions:
  - myselves::change_email
  - myselves::change_password
  - myselves::edit
  - myselves::person_articles_dyta
  - myselves::person_mandates_dyta
  - myselves::person_subscriptions_dyta
  - myselves::show
  - myselves::update
  - people::lost_login
  - people::lost_password
# translation missing: fr-FR, rights, __public__
__public__:
  actions: [sessions::create, sessions::destroy, sessions::new]
