# Réservé aux administrateurs
__admin__:
  actions:
  - products::check
  - products::create
  - products::destroy
  - products::edit
  - products::index
  - products::new
  - products::update
  - sales::index
  - sales::sales_dyta
# Actions sans droits
__not_used__:
  actions: []
# Réservé aux membres en règle
__private__:
  actions:
  - myselves::edit
  - myselves::person_articles_dyta
  - myselves::person_mandates_dyta
  - myselves::person_subscriptions_dyta
  - myselves::show
  - myselves::update
# Réservé à tous les membres (en règle ou pas)
__protected__:
  actions: []
# Accès public sans restrictions
__public__:
  actions:
  - guests::create
  - guests::destroy
  - guests::edit
  - guests::new
  - guests::update
  - home::access_denied
  - home::index
  - home::special
  - myselves::change_email
  - myselves::change_password
  - sale_lines::create
  - sale_lines::decrement
  - sale_lines::destroy
  - sale_lines::edit
  - sale_lines::increment
  - sale_lines::new
  - sale_lines::update
  - sales::cancel
  - sales::check
  - sales::create
  - sales::destroy
  - sales::edit
  - sales::fill
  - sales::finish
  - sales::new
  - sales::pay
  - sales::refuse
  - sales::sale_lines_dyta
  - sales::show
  - sales::update
  - sessions::create
  - sessions::destroy
  - sessions::new
# Gérer les adhésions
subscribing:
  controller: subscriptions
  actions:
  - chase_up
  - create
  - destroy
  - edit
  - index
  - new
  - people_dyli
  - subscriptions_dyta
  - update
