# Réservé aux administrateurs
__admin__:
  actions:
  - countries::create
  - countries::destroy
  - countries::edit
  - countries::index
  - countries::new
  - countries::update
  - intra::configurate
  - languages::create
  - languages::destroy
  - languages::edit
  - languages::index
  - languages::new
  - languages::update
  - products::create
  - products::destroy
  - products::edit
  - products::index
  - products::new
  - products::update
  - sales::index
  - sales::sales_dyta
  - zones::create
  - zones::destroy
  - zones::edit
  - zones::index
  - zones::new
  - zones::refresh
  - zones::show
  - zones::update
# Actions sans droits
__not_used__:
  actions: []
# Réservé aux membres en règle
__private__:
  actions:
  - intra::article
  - intra::authors_dyli
  - intra::folder
  - intra::folder_create
  - intra::folder_delete
  - intra::folder_update
  - intra::gallery
  - intra::image_delete
  - intra::image_detail
  - intra::image_download
  - intra::image_update
  - intra::index
  - intra::member
  - intra::message_send
  - intra::period
  - intra::period_add_member
  - intra::period_delete
  - intra::period_display
  - intra::period_remove_member
  - intra::pick_image
  - intra::preview
  - intra::profile
  - intra::profile_update
  - intra::report
  - intra::report_help
  - intra::reports
  - intra::story
  - intra::students
  - intra::students_dyta
# Réservé à tous les membres (en règle ou pas)
__protected__:
  actions:
  - store::cancelled
  - store::finished
  - store::index
  - store::refused
  - store::summary
# Accès public sans restrictions
__public__:
  controller: home
  actions:
  - article
  - authentication::activate
  - authentication::change_email
  - authentication::change_password
  - authentication::clean_people
  - authentication::index
  - authentication::login
  - authentication::logout
  - authentication::lost_login
  - authentication::lost_password
  - authentication::subscribe
  - authentication::test
  - guests::create
  - guests::destroy
  - guests::edit
  - guests::new
  - guests::update
  - index
  - intra::access_denied
  - intra::approve
  - intra::disapprove
  - sale_lines::create
  - sale_lines::decrement
  - sale_lines::destroy
  - sale_lines::edit
  - sale_lines::increment
  - sale_lines::new
  - sale_lines::update
  - sales::create
  - sales::destroy
  - sales::edit
  - sales::fill
  - sales::new
  - sales::pay
  - sales::sale_lines_dyta
  - sales::show
  - sales::update
  - special
  - store::check_payment
# Gérer les mandats
mandates:
  actions:
  - mandates::create
  - mandates::destroy
  - mandates::edit
  - mandates::index
  - mandates::mandates_dyta
  - mandates::new
  - mandates::people_dyli
  - mandates::update
# Gérer les promotions
promotions:
  actions: [intra::promotion_people_dyta, intra::promotions]
# Gérer la publication
publishing:
  actions:
  - intra::article_activate
  - intra::article_create
  - intra::article_deactivate
  - intra::article_delete
  - intra::article_edit
  - intra::article_to_publish
  - intra::article_update
  - intra::articles
  - intra::articles_dyta
  - rubrics::create
  - rubrics::destroy
  - rubrics::edit
  - rubrics::index
  - rubrics::new
  - rubrics::rubric_articles_dyta
  - rubrics::rubrics_dyta
  - rubrics::show
  - rubrics::update
# Gérer les adhésions
subscribing:
  controller: subscriptions
  actions:
  - chase_up
  - create
  - destroy
  - edit
  - index
  - new
  - people_dyli
  - subscriptions_dyta
  - update
# Gérer les personnes/utilisateurs
users:
  controller: people
  actions:
  - create
  - destroy
  - edit
  - index
  - lock
  - new
  - people_dyta
  - person_articles_dyta
  - person_mandates_dyta
  - person_subscriptions_dyta
  - show
  - unlock
  - update
