# Réservé aux administrateurs
__admin__:
  actions:
  - people::activate
  - people::approve
  - people::create
  - people::destroy
  - people::disapprove
  - people::edit
  - people::index
  - people::lock
  - people::lost_login
  - people::lost_password
  - people::new
  - people::people_dyta
  - people::person_articles_dyta
  - people::person_mandates_dyta
  - people::person_subscriptions_dyta
  - people::subscribe
  - people::unlock
  - people::update
  - products::check
  - products::create
  - products::destroy
  - products::edit
  - products::index
  - products::new
  - products::update
  - sales::index
  - sales::sales_dyta
# Réservé aux membres en règle
__private__:
  actions:
  - articles::authors_dyli
  - articles::create
  - articles::destroy
  - articles::edit
  - articles::help
  - articles::new
  - articles::preview
  - articles::show
  - articles::update
  - myselves::change_email
  - myselves::change_password
  - myselves::edit
  - myselves::person_articles_dyta
  - myselves::person_mandates_dyta
  - myselves::person_subscriptions_dyta
  - myselves::show
  - myselves::update
  - people::show
  - people::story
  - rubrics::rubric_articles_dyta
  - rubrics::show
# Réservé à tous les membres (en règle ou pas)
__protected__:
  actions: []
# Accès public sans restrictions
__public__:
  actions:
  - guests::create
  - guests::destroy
  - guests::edit
  - guests::new
  - guests::update
  - home::access_denied
  - home::index
  - home::special
  - myselves::lost_login
  - myselves::lost_password
  - sale_lines::create
  - sale_lines::decrement
  - sale_lines::destroy
  - sale_lines::edit
  - sale_lines::increment
  - sale_lines::new
  - sale_lines::update
  - sales::cancel
  - sales::check
  - sales::create
  - sales::destroy
  - sales::edit
  - sales::fill
  - sales::finish
  - sales::new
  - sales::pay
  - sales::refuse
  - sales::sale_lines_dyta
  - sales::show
  - sales::update
  - sessions::create
  - sessions::destroy
  - sessions::new
# Gérer la publication
publishing:
  actions:
  - articles::activate
  - articles::articles_dyta
  - articles::deactivate
  - articles::index
  - articles::publish
  - rubrics::create
  - rubrics::destroy
  - rubrics::edit
  - rubrics::index
  - rubrics::new
  - rubrics::rubrics_dyta
  - rubrics::update
# Gérer les adhésions
subscribing:
  controller: subscriptions
  actions:
  - chase_up
  - create
  - destroy
  - edit
  - index
  - new
  - people_dyli
  - subscriptions_dyta
  - update
