# Réservé aux administrateurs
__admin__:
  actions:
  - countries::create
  - countries::destroy
  - countries::edit
  - countries::index
  - countries::new
  - countries::update
  - intra::configurate
  - languages::create
  - languages::destroy
  - languages::edit
  - languages::index
  - languages::new
  - languages::update
  - mandate_natures::create
  - mandate_natures::destroy
  - mandate_natures::edit
  - mandate_natures::index
  - mandate_natures::new
  - mandate_natures::update
  - products::check
  - products::create
  - products::destroy
  - products::edit
  - products::index
  - products::new
  - products::update
  - sales::index
  - sales::sales_dyta
  - zones::create
  - zones::destroy
  - zones::edit
  - zones::index
  - zones::new
  - zones::refresh
  - zones::show
  - zones::update
# Actions sans droits
__not_used__:
  actions: []
# Réservé aux membres en règle
__private__:
  actions:
  - articles::create
  - articles::edit
  - articles::new
  - articles::show
  - articles::update
  - images::create
  - images::destroy
  - images::edit
  - images::index
  - images::new
  - images::show
  - images::update
  - intra::authors_dyli
  - intra::folder
  - intra::folder_create
  - intra::folder_delete
  - intra::folder_update
  - intra::index
  - intra::member
  - intra::period
  - intra::period_add_member
  - intra::period_delete
  - intra::period_display
  - intra::period_remove_member
  - intra::report
  - intra::report_help
  - intra::reports
  - intra::story
  - people::myself
  - people::update_myself
  - promotions::write
  - rubrics::show
# Réservé à tous les membres (en règle ou pas)
__protected__:
  actions: []
# Accès public sans restrictions
__public__:
  controller: home
  actions:
  - article
  - articles::show
  - authentication::activate
  - authentication::change_email
  - authentication::change_password
  - authentication::clean_people
  - authentication::index
  - authentication::login
  - authentication::logout
  - authentication::lost_login
  - authentication::lost_password
  - authentication::subscribe
  - authentication::test
  - guests::create
  - guests::destroy
  - guests::edit
  - guests::new
  - guests::update
  - index
  - intra::access_denied
  - people::approve
  - people::disapprove
  - sale_lines::create
  - sale_lines::decrement
  - sale_lines::destroy
  - sale_lines::edit
  - sale_lines::increment
  - sale_lines::new
  - sale_lines::update
  - sales::cancel
  - sales::check
  - sales::create
  - sales::destroy
  - sales::edit
  - sales::fill
  - sales::finish
  - sales::new
  - sales::pay
  - sales::refuse
  - sales::sale_lines_dyta
  - sales::show
  - sales::update
  - special
  - store::check_payment
# Gérer les mandats
mandates:
  controller: mandates
  actions:
  - create
  - destroy
  - edit
  - index
  - mandates_dyta
  - new
  - people_dyli
  - update
# Gérer les promotions
promotions:
  controller: promotions
  actions: [index, people_dyta, show]
# Gérer la publication
publishing:
  actions:
  - articles::activate
  - articles::articles_dyta
  - articles::deactivate
  - articles::destroy
  - articles::index
  - articles::preview
  - articles::publish
  - rubrics::create
  - rubrics::destroy
  - rubrics::edit
  - rubrics::index
  - rubrics::new
  - rubrics::rubric_articles_dyta
  - rubrics::rubrics_dyta
  - rubrics::update
# Gérer les adhésions
subscribing:
  controller: subscriptions
  actions:
  - chase_up
  - create
  - destroy
  - edit
  - index
  - new
  - people_dyli
  - subscriptions_dyta
  - update
# Gérer les personnes/utilisateurs
users:
  controller: people
  actions:
  - create
  - destroy
  - edit
  - index
  - lock
  - new
  - people_dyta
  - person_articles_dyta
  - person_mandates_dyta
  - person_subscriptions_dyta
  - show
  - unlock
  - update
