# Réservé aux administrateurs
__admin__:
  actions:
  - configurations::edit
  - configurations::update
  - countries::create
  - countries::destroy
  - countries::edit
  - countries::index
  - countries::new
  - countries::update
  - languages::create
  - languages::destroy
  - languages::edit
  - languages::index
  - languages::new
  - languages::update
  - mandate_natures::create
  - mandate_natures::destroy
  - mandate_natures::edit
  - mandate_natures::index
  - mandate_natures::new
  - mandate_natures::update
  - products::check
  - products::create
  - products::destroy
  - products::edit
  - products::index
  - products::new
  - products::update
  - sales::index
  - sales::sales_dyta
  - zone_natures::create
  - zone_natures::destroy
  - zone_natures::edit
  - zone_natures::index
  - zone_natures::new
  - zone_natures::update
  - zones::create
  - zones::destroy
  - zones::edit
  - zones::index
  - zones::new
  - zones::refresh
  - zones::show
  - zones::update
# Actions sans droits
__not_used__:
  actions: []
# Réservé aux membres en règle
__private__:
  actions:
  - articles::create
  - articles::edit
  - articles::help
  - articles::new
  - articles::show
  - articles::update
  - folders::destroy
  - folders::edit
  - folders::report
  - folders::show
  - folders::update
  - images::create
  - images::destroy
  - images::edit
  - images::index
  - images::new
  - images::show
  - images::update
  - members::create
  - members::destroy
  - members::edit
  - members::new
  - members::update
  - myselves::edit
  - myselves::person_articles_dyta
  - myselves::person_mandates_dyta
  - myselves::person_subscriptions_dyta
  - myselves::show
  - myselves::update
  - people::story
  - periods::create
  - periods::destroy
  - periods::edit
  - periods::memberize
  - periods::new
  - periods::show
  - periods::unmemberize
  - periods::update
  - promotions::write
  - rubrics::show
# Réservé à tous les membres (en règle ou pas)
__protected__:
  actions: []
# Accès public sans restrictions
__public__:
  actions:
  - articles::show
  - guests::create
  - guests::destroy
  - guests::edit
  - guests::new
  - guests::update
  - home::access_denied
  - home::article
  - home::index
  - home::special
  - myselves::change_email
  - myselves::change_password
  - people::activate
  - people::approve
  - people::disapprove
  - people::lost_login
  - people::lost_password
  - people::subscribe
  - sale_lines::create
  - sale_lines::decrement
  - sale_lines::destroy
  - sale_lines::edit
  - sale_lines::increment
  - sale_lines::new
  - sale_lines::update
  - sales::cancel
  - sales::check
  - sales::create
  - sales::destroy
  - sales::edit
  - sales::fill
  - sales::finish
  - sales::new
  - sales::pay
  - sales::refuse
  - sales::sale_lines_dyta
  - sales::show
  - sales::update
  - sessions::create
  - sessions::destroy
  - sessions::new
  - store::check_payment
# Gérer les mandats
mandates:
  controller: mandates
  actions:
  - create
  - destroy
  - edit
  - index
  - mandates_dyta
  - new
  - people_dyli
  - update
# Gérer les promotions
promotions:
  controller: promotions
  actions: [index, people2_dyta, show]
# Gérer la publication
publishing:
  actions:
  - articles::activate
  - articles::articles_dyta
  - articles::authors_dyli
  - articles::deactivate
  - articles::destroy
  - articles::index
  - articles::preview
  - articles::publish
  - rubrics::create
  - rubrics::destroy
  - rubrics::edit
  - rubrics::index
  - rubrics::new
  - rubrics::rubric_articles_dyta
  - rubrics::rubrics_dyta
  - rubrics::update
# Gérer les adhésions
subscribing:
  controller: subscriptions
  actions:
  - chase_up
  - create
  - destroy
  - edit
  - index
  - new
  - people_dyli
  - subscriptions_dyta
  - update
# Gérer les personnes/utilisateurs
users:
  controller: people
  actions:
  - create
  - destroy
  - edit
  - index
  - lock
  - new
  - people_dyta
  - person_articles_dyta
  - person_mandates_dyta
  - person_subscriptions_dyta
  - show
  - unlock
  - update
