# translation missing: fr-FR, rights, __protected__
__protected__:
  actions: [answers::fill, suivi::access_denied, suivi::index]
# translation missing: fr-FR, rights, __public__
__public__:
  actions:
  - authentication::index
  - authentication::login
  - authentication::logout
  - authentication::lost_login
  - authentication::lost_password
# translation missing: fr-FR, rights, suivi
suivi:
  actions:
  - answers::accept
  - answers::destroy
  - answers::index
  - answers::lock
  - answers::reject
  - answers::unlock
  - questionnaires::create
  - questionnaires::destroy
  - questionnaires::duplicate
  - questionnaires::edit
  - questionnaires::index
  - questionnaires::new
  - questionnaires::questionnaire_answers_dyta
  - questionnaires::questionnaire_questions_dyta
  - questionnaires::questionnaire_students_dyta
  - questionnaires::questionnaires_dyta
  - questionnaires::show
  - questionnaires::update
  - questionnaires::wake_up_absents
  - questions::create
  - questions::destroy
  - questions::down
  - questions::edit
  - questions::new
  - questions::up
  - questions::update
  - themes::create
  - themes::destroy
  - themes::edit
  - themes::index
  - themes::new
  - themes::themes_dyta
  - themes::update
